# DimensionPortals v0.0.1

overworld:
  # Folder name of the world to use for overworld
  world: world

nether:
  # Folder name of the world to use for nether
  world: nether
  # The number of ticks the player must wait in portal
  # before they get teleported to the nether.
  teleportation-duration: 80
  portal:
    # Frame block surrounding the portal
    frame-block: OBSIDIAN
    # Portal dimensions cap
    max-width: 30
    max-height: 30

end:
  # Folder name of the world to use for end
  world: end
  # The number of ticks the player must wait in portal
  # before they get teleported to the end.
  teleportation-duration: 0